### ISSUE TITLE
IsNonNullOrWhitespaceConverter

### ISSUE THREAD

**Issue by ronymesquita** [saimel/Plugin.XamarinForms.Converters#11]
This converter can be useful to hide elements with `IsVisible` when a string is null or has only whitespace.

```csharp
public class IsNonNullOrWhitespaceConverter : IValueConverter
{
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value is string text && !string.IsNullOrWhiteSpace(text);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value;
        }
}
```

Could you add this?

Thanks.

**Comment by saimel** [comment]
Hi @ronymesquita 
Thanks very much for this contibuttion, I'll be glad to add it as another useful converter.
Don't you prefer to create a PR and get the credit for that?

**Comment by ronymesquita** [comment]
Hello.
Yes, I'll create the pull request.
