### ISSUE TITLE
BoolToStringConverter

### ISSUE THREAD

**Issue by tranb3r** [saimel/Plugin.XamarinForms.Converters#6]
I'd be interested in having a BoolToStringConverter.
With two string parameters: TrueValue (string to return when bool is true), FalseValue (string to return when bool is false).
What do you think ?

**Comment by saimel** [comment]
@tranb3r thanks for your suggestion. I decided to go farther so I added **BoolToObjectConverter** which allows to define two possible values to return as you suggested, but not only `string`, you might set any type deriving from `object`.
