### ISSUE TITLE
BoolToObjectConverter : ConvertBack does not work

### ISSUE THREAD

**Issue by tranb3r** [saimel/Plugin.XamarinForms.Converters#8]
The ConvertBack method in BoolToObjectConverter always returns false.
I think the reason for this bug is that you're using the == operator instead of Equal when comparing both objects.
Could you please fix it ?
Thanks

**Comment by saimel** [comment]
Hi @tranb3r , next couple of weeks I'm gonna be really busy at work, I can't promise I'll fix it. I don't think using `Equals()` would make any difference, maybe you must consider to override the `Equals()` method on your class? If you consider the `==` will solve the issue, feel free to fix it and add a PR, I'll be glad to review it and merge it.

**Comment by tranb3r** [comment]
Thank you @saimel for answering rapidly !
This is not urgent at all and I totally understand if you do not have the time to work on it.

What I'm 100% sure is that `==` does not work since it compares object references.
I'll do more tests, and submit a PR with a fix.

**Comment by saimel** [comment]
Pull Request form @tranb3r merged!
